services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_erudio
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3308:3306
    expose:
      - 3306
    networks:
      - erudio-network
  rest-with-spring-boot-erudio:
    image: leandrocgsi/rest-with-spring-boot-erudio
    restart: always
    build: ./rest-with-spring-boot-and-java-erudio
    working_dir: /rest-with-spring-boot-and-java-erudio
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erudio-network

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge

volumes:
  portainer_data: